[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "undertaker-auditor"
version = "0.3.1"
description = "Find old, privileged scheduled jobs before they become operational risk."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
  { name = "David Sarkisyan" }
]
keywords = [
  "cron",
  "scheduled-tasks",
  "systemd",
  "windows",
  "security-audit",
  "defensive-security"
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: System Administrators",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Security",
  "Topic :: System :: Systems Administration"
]

[project.scripts]
uk = "undertaker:main"
undertaker = "undertaker:main"

[tool.setuptools]
py-modules = ["undertaker"]
